server:
  servlet:
    encoding:
      force: true
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    #?? ???
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    .org.hibernate: DEBUG
    
    #???? ? ????
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


